### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by KavishShah09** [Naman-2001/MarioPlan#1]
Actual: "A project Planner made using React, React Hooks and Redux with a database deployed on firebase.
It notifies you wehn someone joins the group and when someone add a project."

Should be: "A project Planner made using React, React Hooks and Redux with a database deployed on firebase.
It notifies you when someone joins the group and when someone add a project."

**Comment by KavishShah09** [comment]
You should close this issue if you've done the changes instead of me closing it for you

**Comment by Naman-2001** [comment]
From where can I close the issue..I didn't posted it I suppose.

**Comment by Naman-2001** [comment]
Also are you an experienced web developer?

**Comment by KavishShah09** [comment]
You close it at the bottom of the conversation, also I am not that experienced
