### ISSUE TITLE
AuthIsLoaded

### ISSUE THREAD

**Issue by KavishShah09** [Naman-2001/MarioPlan#2]
Change App.js to this
```js
import React from 'react'
import { BrowserRouter, Switch, Route } from 'react-router-dom'
import Navbar from './components/layout/Navbar'
import DashBoard from './components/dashboard/DashBoard'
import ProjectDetails from './components/projects/ProjectDetails'
import SignIn from './components/auth/SignIn'
import SignUp from './components/auth/SignUp'
import CreateProject from './components/projects/CreateProject'
import { isLoaded } from 'react-redux-firebase'
import { useSelector } from 'react-redux'

function AuthIsLoaded({ children }) {
	const auth = useSelector((state) => state.firebase.auth)
	if (!isLoaded(auth)) return <div>splash screen...</div>
	return children
}

function App() {
	return (
		<BrowserRouter>
			<AuthIsLoaded>
				<div className="App">
					<Navbar />
					<Switch>
						<Route exact path="/" component={DashBoard} />
						<Route path="/project/:id" component={ProjectDetails} />
						<Route path="/signin" component={SignIn} />
						<Route path="/signup" component={SignUp} />
						<Route path="/create" component={CreateProject} />
					</Switch>
				</div>
			</AuthIsLoaded>
		</BrowserRouter>
	)
}
export default App
```

**Comment by Naman-2001** [comment]
Thank You so much for this method. I have been looking for this solution
but could not find it. I will make the changes later today.
But I wonder from where you get my github repo? I did't share it anywhere
as far as I remember.

**Comment by KavishShah09** [comment]
I also followed along The Net Ninja's playlist for this project recently but it was outdated with the latest libraries so instead of writing the changes myself I just looked if someone else had done it and searched github with most recently updated filter presuming they would've used hooks(which you have a bit but could do more using useSelector and useDispatch instead of mapStateToProps and mapDispatchToProps and also use useFirestoreConnect hooks instead of fireStoreConnect since you are using functional components and not class components you should do everything using hooks) and found this repo. I cloned it and saw you hadn't done the authIsLoaded yet so just suggested that change

**Comment by Naman-2001** [comment]
oh! thanks brother. Much appreciated
